language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo test --verbose --all
  - cargo fmt --all -- --check
  - cargo clippy --all
